CREATE TABLE IF NOT EXISTS `db`.`company` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `identification` VARCHAR(100) NOT NULL UNIQUE,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `status` INT(1) NOT NULL DEFAULT 1 COMMENT '0 = Inactive ; 1 = Active',
  `phone` INT(9) NULL,
  `mail` VARCHAR(100) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));
  
  CREATE TABLE IF NOT EXISTS `db`.`log_enviame` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `payload` TEXT NOT NULL,
  `response` TEXT NULL,
  `status` INT(1) NOT NULL DEFAULT 1 COMMENT '0 = Create ; 1 = processed ; 2 = Error',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));